Bogus -Wtype-limits when static assert checks a static const
only happens w/ gcc4.8 -Wextra, and only when comparison happens on a
static constexpr contstant that is otherwise unused in the test block

> In file included from test/Numbers/parseNumber.ipp:29:0,
>                  from test/Numbers/parseInteger32.cpp:9:
> test/Numbers/parseInteger32.cpp: In function ‘void C_A_T_C_H_T_E_S_T_51()’:
> test/Numbers/parseInteger32.cpp:98:58: error: comparison is always true due to limited range of data type [-Werror=type-limits]
>      STATIC_REQUIRE(std::numeric_limits<JsonInteger>::min() > s64_min);
>                                                           ^
> test/Numbers/parseInteger32.cpp:106:58: error: comparison is always true due to limited range of data type [-Werror=type-limits]
>      STATIC_REQUIRE(std::numeric_limits<JsonInteger>::max() < s64_max);
>                                                           ^
> test/Numbers/parseInteger32.cpp: In function ‘void C_A_T_C_H_T_E_S_T_56()’:
> test/Numbers/parseInteger32.cpp:124:66: error: comparison is always true due to limited range of data type [-Werror=type-limits]
>      STATIC_REQUIRE(std::numeric_limits<JsonUnsignedInteger>::max() < u64_max);